"""Chat API request and response schemas."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Chat query input request model."""

    question: str = Field(
        min_length=2,
        max_length=2000,
        description="Natural language question query.",
        examples=["What are the main findings in the report?"],
    )
    top_k: Optional[int] = Field(
        default=None,
        ge=1,
        le=20,
        description="Optional top-K chunks retrieval count override.",
    )


class SourceCitationSchema(BaseModel):
    """Source document citation schema."""

    document_name: str = Field(description="Source document name.")
    page_number: int = Field(description="Page number citation.")
    chunk_id: str = Field(description="Vector chunk ID.")
    score: float = Field(description="Similarity relevance score.")
    snippet: str = Field(description="Text passage preview snippet.")


class RetrievedChunkSchema(BaseModel):
    """Retrieved chunk detailed payload model."""

    chunk_id: str = Field(description="Vector chunk ID.")
    document_name: str = Field(description="Source document name.")
    page_number: int = Field(description="Page number.")
    score: float = Field(description="Relevance score.")
    text: str = Field(description="Full text content of chunk.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata dictionary.")


class ChatResponse(BaseModel):
    """Grounded RAG chat query response model."""

    answer: str = Field(description="Grounded answer generated by local Ollama model.")
    confidence: Optional[float] = Field(description="Highest similarity score match.")
    sources: List[SourceCitationSchema] = Field(description="List of source citations.")
    retrieved_chunks: List[RetrievedChunkSchema] = Field(description="Full retrieved text chunks.")
    metrics: Dict[str, float] = Field(default_factory=dict, description="Latency metrics in ms.")
